import { NextRequest, NextResponse } from 'next/server';
import { getPolicyId } from '@/lib/policyUtils';

/**
 * Get policy ID for client-side use
 * Auto-generates from mnemonic if not manually set
 */
export async function GET(request: NextRequest) {
  try {
    const policyId = getPolicyId();

    return NextResponse.json({
      policyId,
      isAutoGenerated: !process.env.POLICY_ID,
      message: process.env.POLICY_ID
        ? 'Using manually configured policy ID'
        : 'Auto-generated from mnemonic'
    });
  } catch (error: any) {
    console.error('Error getting policy ID:', error);
    return NextResponse.json(
      {
        error: 'Failed to get policy ID',
        details: error.message,
        hint: 'Make sure MINTTING_WALLET_OUTPUT_MNEMONIC is set in .env'
      },
      { status: 500 }
    );
  }
}
